### ISSUE TITLE
Error tras instalar Plugin Federador

### ISSUE THREAD

**Issue by Cheomm88** [damalaga/ckanext-federador#1]
Hola,
estamos tratando de instalar el plugin federador (https://github.com/damalaga/ckanext-federador) tras llevar a cabo la instalación y llamar a la ruta http://localhost/catalog/malaga.rdf nos devuelve un error 500.

La versión de CKAN instalada es la 2.7.2, el plugin dcat está instalado desde el repositorio oficial.

Mirando el log hemos podido comprobar que el error viene de tratar de leer la entrada u'' en la lista de los tipos mime.

Error - <type 'exceptions.KeyError'>: u''

[...]

File '/usr/lib/ckan/default/src/ckanext-federador/ckanext/federador/templates/catalog/malaga.rdf', line 67 in top-level template code
  <dct:format>{% set typefiles=h.fed_filetype(_rsc_dict['format']) %}
File '/usr/lib/ckan/default/src/ckanext-federador/ckanext/federador/filetypes.py', line 72 in mimetype_extension
  return list_filetype[filetype.lower()]
KeyError: u''

Viendo el error decidimos poner un try catch en la función  mimetype_extension

def mimetype_extension(filetype):
	try:
		return list_filetype[filetype.lower()]
	except KeyError:
		print("Key ", filetype,  "does not exist!")

Lo que nos genera en el log la siguiente entrada:

('Key ', u'', 'does not exist!')

Entonces la llamada si devuelve información, pero no se trata de un RDF, nos devuelve información sin los tags de XML/RDF.

**Comment by damalaga** [comment]
Hola,

Antes de nada gracias por la aportación, incluiremos el try - except en la próxima versión del plugin,

Por lo que estoy viendo, el problema puede ser que alguno de vuestros recursos no tiene el campo formato relleno en vuestra plataforma CKAN, por favor, comprueba si este es el problema y me dices.

El formato tiene que estar relleno, al ser obligatorio en la federación de red.es.

Un saludo.

**Comment by Cheomm88** [comment]
Hola,
he revisado y existía un dataset sin formato, al añadirle el formato y probado a ejecutar
/catalog/malaga.rdf

El resultado ha sido un listado de elementos sin etiquetas XML con la información de los diferentes datasets.

Por ejemplo el primer elemento que aprece sale así:

> http://localhost 10 10 bytes 2017-02-27T09:26:44 2018-05-22T11:30:34 es http://localhost/dataset/agenda-cultural Agenda Cultural False Agenda Cultural Cultura y ocio cultura eventos ocio 2018-05-02T13:06:26 2018-05-02T13:07:51 es http://www.opendefinition.org/licenses/cc-by http://localhost/dataset/agenda-cultural/resource/ce50462d-47ee-4687-9338-f9984c92f620 eventosculturales.csv http://localhost/dataset/d3ee21f9-5f6c-4a90-b6c6-3bc279a88024/resource/ce50462d-47ee-4687-9338-f9984c92f620/download/eventosculturales.csv text/csv CSV 64316

¿Es correcto? 

En la ejecución no me ha salido nada en el log referente al error.

**Comment by Cheomm88** [comment]
He creado un PULL REQUEST [1] pra que puedan integrar el cambio cuando lo consideren.

[1] : https://github.com/damalaga/ckanext-federador/pull/2

**Comment by damalaga** [comment]
Hola,

Por favor, haz un "ver código fuente de la página" que te genera el federador, a ver si tiene formato XML.

Para que te hagas una idea del formato correcto, cuando generamos el rdf de datosabiertos.malaga.eu, nos genera este fichero https://datosabiertos.malaga.eu/recursos/federacion/fed-malaga.rdf y este enlace es el que federamos.

Ya nos dices....

**Comment by Cheomm88** [comment]
Al darle ver "código fuente" se ve el formato XML, entiendo que pasándole la URL al federador de datos gob no habrá mayores problemas.

Muchas gracias!

**Comment by damalaga** [comment]
Exacto.
Saludos
